# Copyright (C) 2020-2023 Simon Josefsson
#
# This file is part of GNU Libidn.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

stages:
 - quick
 - bootstrap
 - tarball

default:
  interruptible: true
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
    - "*.tar.gz"
    - ./*.log
    - ./config.h
    - ./**/*.log

Q-Debian-testing:
  image: $CI_REGISTRY/libidn/build-images:libidn-mini-Debian-testing
  stage: quick
  script:
  - time ./bootstrap --skip-po --no-git
  - time ./configure --disable-doc
  - time make syntax-check
  - time make V=1
  - time make check VERBOSE=t V=1
  - git diff --exit-code # nothing should change version controlled files

# https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
sast:
  stage: quick
  variables:
    SAST_EXCLUDED_PATHS: gnulib
include:
- template: Security/SAST.gitlab-ci.yml

# https://www.synopsys.com/blogs/software-security/integrating-coverity-scan-with-gitlab-ci/
Coverity:
  image: $CI_REGISTRY/libidn/build-images:libidn-mini-Debian-testing
  stage: bootstrap
  only:
    refs:
      - master
      - coverity
  allow_failure: true
  before_script:
  - apt-get update -qq -y
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -q curl
  script:
  - test -n "$COVERITY_SCAN_TOKEN" && test -n "$COVERITY_SCAN_PROJECT_NAME"
  - curl -o /tmp/cov-analysis-linux64.tgz https://scan.coverity.com/download/linux64
    --form project=$COVERITY_SCAN_PROJECT_NAME --form token=$COVERITY_SCAN_TOKEN
  - sha1sum /tmp/cov-analysis-linux64.tgz
  - tar xfz /tmp/cov-analysis-linux64.tgz
  - time ./bootstrap --skip-po
  - time ./configure --enable-gcc-warnings --disable-doc CFLAGS="-g -Og"
  - cov-analysis-linux64-*/bin/cov-build --dir cov-int make check -j$(nproc)
  - tar cfz cov-int.tar.gz cov-int
  - curl https://scan.coverity.com/builds?project=$COVERITY_SCAN_PROJECT_NAME
    --form token=$COVERITY_SCAN_TOKEN --form email=$GITLAB_USER_EMAIL
    --form file=@cov-int.tar.gz --form version="`git describe --tags`"
    --form description="`git describe --tags` / $CI_COMMIT_TITLE / $CI_COMMIT_REF_NAME:$CI_PIPELINE_ID"
  artifacts:
    expire_in: 1 week
    paths:
      - cov-int/*.txt

B-Alpine:
  image: alpine:latest
  stage: bootstrap
  before_script:
  - apk update
  - apk add gcc make libc-dev git autoconf automake libtool gettext-dev gperf gengetopt patch coreutils
  script:
  - time ./bootstrap --skip-po
  - time ./configure --disable-doc
  - time make syntax-check
  - time make V=1 VERBOSE=t
  - time make check V=1 VERBOSE=t
  - git diff --exit-code # nothing should change version controlled files

B-Debian9:
  image: $CI_REGISTRY/libidn/build-images:libidn-Debian9
  stage: bootstrap
  script:
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java
  - time make check V=1 VERBOSE=t
  - time make dist
  - time make syntax-check
  - git diff --exit-code # nothing should change version controlled files

B-Debian12:
  image: $CI_REGISTRY/libidn/build-images:libidn-Debian12
  stage: bootstrap
  before_script:
  - apt-get update
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq wget
  script:
  - time ./bootstrap --no-git
  - time ./configure --enable-java
  - time make syntax-check
  - time make check V=1 VERBOSE=t
  - time make dist
  - git diff --exit-code # nothing should change version controlled files

B-Debian-testing:
  image: $CI_REGISTRY/libidn/build-images:libidn-Debian-testing
  stage: bootstrap
  script:
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java
  - time make check V=1 VERBOSE=t
  - time make distcheck
  - make install
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq man
  - git clone --depth=1 https://salsa.debian.org/debian/libidn.git debian-libidn
  - debian-libidn/debian/tests/idn
  - debian-libidn/debian/tests/libidn
  - git diff --exit-code # nothing should change version controlled files

B-Fedora-latest:
  image: $CI_REGISTRY/libidn/build-images:libidn-Fedora-latest
  stage: bootstrap
  script:
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java
  - time make check V=1 VERBOSE=t
  - time make distcheck
  - git diff --exit-code # nothing should change version controlled files

B-Trisquel11:
  image: $CI_REGISTRY/libidn/build-images:libidn-Trisquel11
  stage: bootstrap
  script:
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java
  - time make check V=1 VERBOSE=t
  - time make dist
  - time make syntax-check
  - git diff --exit-code # nothing should change version controlled files

B-Ubuntu-latest:
  image: $CI_REGISTRY/libidn/build-images:libidn-Ubuntu-latest
  stage: bootstrap
  script:
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java
  - time make check V=1 VERBOSE=t
  - time make distcheck
  - git diff --exit-code # nothing should change version controlled files

B-MacOS13Xcode14:
  image: macos-13-xcode-14
  stage: bootstrap
  tags:
  - saas-macos-medium-m1
  before_script:
  - env HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_UPGRADE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install autoconf automake libtool gengetopt help2man texinfo
  script:
  - time ./bootstrap --skip-po
  - time ./configure --enable-gcc-warnings
  - make syntax-check
  - make -j$(nproc) check V=1 VERBOSE=t
  - git diff --exit-code # nothing should change version controlled files

B-clang:
  image: silkeh/clang:15-bullseye
  stage: bootstrap
  before_script:
  - clang --version
  - apt-get update -qq
  - apt-get install -qqy --no-install-recommends make git autoconf automake libtool gettext autopoint cvs texinfo texlive texlive-plain-generic texlive-extra-utils help2man gtk-doc-tools dblatex valgrind gengetopt transfig mono-mcs gperf default-jdk-headless
  script:
  - time ./bootstrap --skip-po
  - time ./configure CC="clang-15 -std=gnu2x"
  - time make V=1
  - time make check V=1 VERBOSE=t
  - git diff --exit-code # nothing should change version controlled files

B-gcc:
  image: gcc:latest
  stage: bootstrap
  before_script:
  - gcc --version
  - apt-get update -qqy
  - apt-get install -qqy --no-install-recommends make git autoconf automake libtool gettext autopoint cvs help2man valgrind gengetopt gperf
  script:
  - time ./bootstrap --skip-po
  - time ./configure --enable-gcc-warnings --disable-doc CC="/usr/local/bin/gcc -std=gnu2x"
  - time make V=1
  - time make syntax-check
  - time make check VERBOSE=t
  - git diff --exit-code # nothing should change version controlled files

AlmaLinux:
  image: almalinux:8
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - dnf -y install make gcc diffutils valgrind
  script:
  - tar xfa libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - time ./configure
  - time make check V=1 VERBOSE=t

Alpine:
  image: alpine:latest
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - apk update
  - apk add build-base
  script:
  - tar xfz libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - time ./configure
  - time make check V=1 VERBOSE=t

ArchLinux:
  image: archlinux:latest
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - pacman -Syu --noconfirm make gcc diffutils
  script:
  - tar xfz libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - time ../configure
  - time make check V=1 VERBOSE=t

CentOS7:
  image: centos:7
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - yum -y install make gcc diffutils valgrind
  script:
  - tar xfa libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - time ./configure
  - time make check V=1 VERBOSE=t

Debian10:
  image: debian:10-slim
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - apt-get update
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make gcc
  script:
  - tar xfz libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - time ../configure
  - time make check V=1 VERBOSE=t

Fedora-latest:
  image: fedora:latest
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - dnf -y install make gcc diffutils valgrind
  script:
  - tar xfz libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - time ./configure
  - time make check V=1 VERBOSE=t

Ubuntu12.04:
  image: ubuntu:12.04
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - perl -pi -e 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list
  - apt-get update -q
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make gcc valgrind
  script:
  - tar xfa libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - time ./configure
  - time make check V=1 VERBOSE=t

Ubuntu14.04:
  image: ubuntu:14.04
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - apt-get update -qq
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make gcc valgrind
  script:
  - tar xfa libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - time ./configure --disable-tld
  - time make check V=1 VERBOSE=t

Ubuntu-rolling:
  image: ubuntu:rolling
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - apt-get update -qq
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq git make gcc valgrind gtk-doc-tools texinfo texlive texlive-plain-generic
  script:
  - tar xfa libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - time ./configure
  - time make check V=1 VERBOSE=t
  - make distcheck

Mingw32:
  image: debian:12-slim
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - dpkg --add-architecture i386
  - apt-get update -qq
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make mingw-w64 wine wine32 libwine libwine:i386 binfmt-support wine-binfmt
  - update-binfmts --enable wine
  script:
  - tar xfz libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - time ../configure --host=i686-w64-mingw32 CC='i686-w64-mingw32-gcc -static-libgcc'
  - time make check V=1 VERBOSE=t

Mingw64:
  image: debian:12-slim
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - apt-get update -qq
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make mingw-w64 wine wine64 binfmt-support wine-binfmt
  - update-binfmts --enable wine
  script:
  - tar xfz libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - time ../configure --host=x86_64-w64-mingw32
  - time make check V=1 VERBOSE=t

Armcross:
  image: debian:12-slim
  stage: tarball
  needs: [B-Trisquel11]
  before_script:
  - apt-get update -qq
  - env DEBIAN_FRONTEND=noninteractive apt-get install -y -qq make gcc-arm-linux-gnueabi qemu-user qemu-user-binfmt file binfmt-support
  - update-binfmts --enable qemu-arm
  script:
  - tar xfz libidn-*.tar.gz
  - cd `ls -d libidn-* | grep -v tar.gz`
  - mkdir b
  - cd b
  - ../configure --host=arm-linux-gnueabi CFLAGS="-static --static"
  - make V=1
  - file src/idn
  - LANG=C.UTF-8 qemu-arm src/idn --debug foo
  - time make check V=1 VERBOSE=t

.pages:
  image: $CI_REGISTRY/libidn/build-images:libidn-Debian-testing
  stage: bootstrap
  script:
  - time ./bootstrap --skip-po --no-git
  - time ./configure --enable-java --enable-gtk-doc --enable-gtk-doc-pdf
  - time make V=1
  - mkdir -p public
  - rm -rf public/reference
  - mv doc/reference/html public/reference
  - make web-manual
  - rm -rf public/manual
  - mv doc/manual public/manual
  artifacts:
    when: on_success
    paths:
      - public

pages:
  extends: .pages
  only:
    - master

pages-test:
  extends: .pages
  except:
    - master
